import Head from "next/head";
import Image from "next/image";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import laser from "../public/laser.jpg";
import web3ducation from "../public/web3ducation.png";
import kaveguilddiscord from "../public/kaveguilddiscord.png"
import dict1 from "../public/dict1.jpg";
import dict2 from "../public/dict2.jpg";
import dict3 from "../public/dict3.jpg";
import ethvietnam from "../public/ethvietnam.jpg";
import p1 from "../public/laser.jpg";
import p2 from "../public/p2.jpg";
import p3 from "../public/p3.jpg";
import p4 from "../public/p4.jpg";
import p5 from "../public/p5.jpg";
import p6 from "../public/p6.jpg";
import p7 from "../public/p7.jpg";
import p9 from "../public/p9.jpg";
import p10 from "../public/p10.jpg";
import p11 from "../public/p11.jpg";
import p12 from "../public/p12.jpg";
import cointelegraph from "../public/cointelegraph.jpg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mark Manansala | Web3 Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">manansala.eth</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://wa.me/639153530821"
                >
                  Let&apos;s be fren!
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl " >
              Mark Manansala
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Senior Full Stack Web3 Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Based in Dubai, I have over 12 years of development experience, with a strong focus on the Web3 space since 2017.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/0xManansala"><AiFillTwitterCircle /></a>
              <a href="https://www.linkedin.com/in/davegala09/"><AiFillLinkedin /></a>
              <a href="https://www.instagram.com/0xmanansala/"><AiFillInstagram /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={laser} layout="fill" objectFit="cover" alt="mark manansala" />
            </div>
          </div>
        </section>
        <section>

          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I began coding in 2012 and have spent six years in the Web3 space. I specialize in smart contract development, decentralized applications (DApps), decentralized finance (DeFi), and NFT marketplaces. I also founded a Web3 academy to train new developers and offer blockchain consulting services.

            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including blockchain development, marketing and teaching.
            </p>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Stuff I do:</h3>

          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="mark manansala" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Expertise
              </h3>
              <p className="py-2">Development: Skilled in Web3 libraries, EVM, frontend, and backend development.</p>
              <p className="text-gray-800 py-1">Marketing: Provide robust Web3 marketing solutions including community management and social media marketing.</p>
              <p className="text-gray-800 py-1">Consulting: Expertise in project management, blockchain protocols, and community building.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="mark manansala" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Accomplishments
              </h3>
              <p className="py-2">Speaker: Frequent speaker at blockchain conferences in the Philippines, Thailand, Vietnam, Indonesia, Singapore, and Dubai.</p>
              <p className="text-gray-800 py-1">Recognition: Featured in various blockchain and crypto industry events.</p>
              <p className="text-gray-800 py-1">Founder: Established a Web3 academy focused on educating and mentoring new developers.</p>
              <p className="text-gray-800 py-1">Consultant: Provided blockchain consulting and advisory services to numerous companies.</p>
              <p className="text-gray-800 py-1">Projects: Successfully launched and managed multiple Web3 projects, demonstrating expertise in development and strategy.</p>

            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="mark manansala" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Stuff I do lately:
              </h3>

              <p className="text-gray-800 py-1">Kave Guild: Your Web3 Ally: Actively building a community and promoting Blockchain & Web3 Technology in the Philippines, encouraging students, professionals and all aspects of life to learn more about this opportunity.</p>
              <p className="py-2">Web3ducation: An educational platform focused on teaching Web3 technologies and blockchain development.</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Places I&apos;ve been:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">

              BLOCKCHAIN CONFERENCES AND TALK SHOWS <br></br>
              THAILAND - PHILIPPINES - VIETNAM - INDONESIA - SINGAPORE - DUBAI
            </p>
          </div>
          <div className="grid grid-cols-3 gap-4">
            
          <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={dict1}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={dict2}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={dict3}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p1}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p2}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p3}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p4}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p5}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p6}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p7}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={ethvietnam}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p9}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p10}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p11}
              />
            </div>
            <div className="sddd">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={p12}
              />
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Where I got recently featured:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">


            </p>
          </div>
          <div className="grid grid-cols-2 gap-4">

            <div className="sddd">

              <video class="testgame" muted autoPlay loop width="100%">
                <source src={"https://markdavemanansala.github.io/images/superverse.mp4"} type="video/mp4" />
              </video>
            </div>

            <div>
              <iframe class="testgame" width="100%" height="100%" src="https://www.youtube.com/embed/Ry3ggJCK3Gg"
                title="Mark Manansala - Web3 Developer" frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
            </div>
            <div>
              <a
                href="https://cointelegraph.com/news/turning-losses-to-wins-how-a-ponzi-victim-became-a-crypto-evangelist">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  alt="mark manansala"
                  height={"100%"}
                  layout="responsive"
                  src={cointelegraph}
                /></a>
            </div>
            <div>
              <a
                href="https://www.facebook.com/DICTDavaoRegion/posts/pfbid0DNz5YjE5vGhWxFpkk769Xepg5tBLg2wWnBVPZvDNVDKrGvXqhdNTw34u9JurFdRYl">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  alt="mark manansala"
                  height={"100%"}
                  layout="responsive"
                  src={dict2}
                /></a>
            </div>
          </div>
        </section>


        <section className="py-10">

          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Things I&apos;m working on lately ...</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">


            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={web3ducation}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={kaveguilddiscord}
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                                  width={"100%"}
                  alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                                  width={"100%"}
                  alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                                  width={"100%"}
                  alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                                  width={"100%"}
                  alt="mark manansala"
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
